---
name: Travis Spear
position: ""
address: ""
phone: 303 263 4842
email: "travisspear@gmail.com"
linkedin: travis-spear
date: "`r format(Sys.time(), '%B %Y')`"
footer: "test footer"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Summary
Highly motivated data professional with 4+ years of experience utilizing R and Python for statistics, predictive analytic, and machine learning. Skilled in managing data operations and implementing solutions from collection to modeling. Proven ability to communicate the impact of analytical findings to a wide range of audiences through innovative data visualizations. 


# Career Interests
 * Natural Language Processing
 * Medical/Healthcare Applications
 * Data Stream/IOT Analytics
 * Business Analytics


# Core Skills  
**Primary Languages** : R, Python, SQL  
**Frameworks** : Shiny, ggplot, Tensorflow, caret, Keras, Flask, Django 
**Competencies** : Data Mining and Cleaning, Data Visualization, Dashboard Development, Business Analytics, Forecasting, Natural Language Processing, Statistics, Experimental Design, Machine Learning. Artificial Intelligence, R Package Development


# Professional Experience
**2019 - Present : Senior Analyst**  
**MedAware Systems Inc.**  

*Description*

Lead analytic developer in a start-up environment. Developed data processing pipelines to streamline meta-analytic report generation for clients. 

*Key Responsibilities* 
  
  * Implemented data cleaning, quality assurance, and report generation scripts using R and SQL to greatly reduce report generation times.
  * Managed the planning, collection, and analysis of multiple client data sets concurrently.
  * Authored medical meta-analyses aggregating hundreds of clinical trials.
  * Developed algorithms to mine features from raw text with upwards of 90% precision.
  * Mentored junior analysts in R/SQL and led ongoing training efforts.
  * Deployed Shiny dashboard to track company and project KPI's.
  

**2016 - 2019 : Data Analyst / Medical Research Scientist**  
**MedAware Systems Inc.**  

*Description*

Dynamic, interdisciplinary role with exposure to biostatistics, business, and software development.  

*Key Responsibilities* 
    
  *	Managed the integrity and completeness of data acquisition from thousands of clinical trials.
  * Provided analytic support to biostatisticians including data cleaning, modeling, and visualization.
  * Maintained R package of statistical functions, data cleaning, and quality assurance tools.
  * Automated outlier and anomaly detection processes using R to ensure the integrity of customer facing data.
  * Redesigned data collection framework to enrich analytic capabilities.
  * Assisted in quality assurance of C#/.NET applications.


**2012 : Undergraduate Research Assistant**  
**Colorado State University**  

*Key Responsibilities*  

  * Investigated Histone binding kinetics utilizing Fluorescence Resonance Energy Transfer (FRET) Assays of purified proteins


# Other Experience
**2014 : Microbiology Teaching Assistant**  
**Colorado State University**  

*Key Repsonsibilities*  

  * Lectured large student groups and led review sessions for up to 100 students
  * Co-authored tests and assisted in grading assignments
  

# Education  
**2019-Present : M.S. Data Science - University of Denver** 


**2014-2015 : M.S. Biomedical Science - Colorado State University** 


**2010-2014 : B.S Biomedical Science - Colorado State University**


# Projects
[R/Shiny/SQL - COVID-19 Literature Dashboard](https://travisspear.shinyapps.io/COVID19)

[R/Shiny - PubMed Literature Network Generator](https://travisspear.shinyapps.io/PubMed_Networks)

[R/SQL - Literature Bias in alzheimer's Disease (AAN 2019)](/post/aan2019/)



